mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=31ebbd9411ffb4
mail.password=c1f0cbbe47ef47
app.mail=awishkanipun62@gmail.com
app.name=ReadTrades
app.url=http://localhost:8080/ReadTrades
app.public.url=http://localhost:8080/ReadTrades